/** AUTO-GENERATED by scripts/sync-catalog-agents.mjs — do not edit. */
import { buildCatalogAgentExports } from '../agent-catalog/build-agent-module.ts';

const agent = buildCatalogAgentExports("content-studio");

export const route = agent.route;
export const description = agent.description;
export default agent.definition;
