import esbuild from 'esbuild';
import { copyFileSync, mkdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outRoot = path.join(root, '.vercel', 'output');
const funcDir = path.join(outRoot, 'functions', 'index.func');
const staticDir = path.join(outRoot, 'static');

// Also keep a copy under api/ for local inspection (gitignored).
const apiDir = path.join(root, 'api');

rmSync(outRoot, { recursive: true, force: true });
mkdirSync(funcDir, { recursive: true });
mkdirSync(staticDir, { recursive: true });
mkdirSync(apiDir, { recursive: true });
writeFileSync(path.join(staticDir, '.gitkeep'), '');

// Native / optional deps that must not be bundled.
const external = [
  'pg-native',
  'cpu-features',
  'bufferutil',
  'utf-8-validate',
];

const outfile = path.join(funcDir, 'index.js');

await esbuild.build({
  entryPoints: [path.join(root, 'scripts/vercel-entry.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  external,
  logLevel: 'info',
  banner: {
    js: '/* Vercel Build Output API bundle — generated by scripts/build-vercel.mjs */',
  },
});

const { size } = statSync(outfile);
if (size < 100_000) {
  throw new Error(`serverless bundle suspiciously small (${size} bytes)`);
}

writeFileSync(
  path.join(funcDir, '.vc-config.json'),
  `${JSON.stringify(
    {
      runtime: 'nodejs22.x',
      handler: 'index.js',
      launcherType: 'Nodejs',
      maxDuration: 300,
    },
    null,
    2,
  )}\n`,
);

writeFileSync(
  path.join(outRoot, 'config.json'),
  `${JSON.stringify(
    {
      version: 3,
      routes: [
        { handle: 'filesystem' },
        { src: '/(.*)', dest: '/index' },
      ],
    },
    null,
    2,
  )}\n`,
);

// Mirror for local debugging (not used by Build Output API deploy).
copyFileSync(outfile, path.join(apiDir, 'index.js'));

console.log(
  `Vercel Build Output: .vercel/output/functions/index.func/index.js (${(size / 1024 / 1024).toFixed(1)} MB)`,
);
