import esbuild from 'esbuild';
import { spawnSync } from 'node:child_process';
import { cpSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outRoot = path.join(root, '.vercel', 'output');
const funcDir = path.join(outRoot, 'functions', 'index.func');
const staticDir = path.join(outRoot, 'static');

const regions = (process.env.VERCEL_REGIONS ?? 'hkg1')
  .split(',')
  .map((r) => r.trim())
  .filter(Boolean);

if (process.env.DATABASE_URL?.trim()) {
  console.log('Running db:migrate before Vercel bundle...');
  const migrate = spawnSync('npm', ['run', 'db:migrate'], {
    cwd: root,
    stdio: 'inherit',
    env: process.env,
  });
  if (migrate.status !== 0) {
    throw new Error('db:migrate failed during Vercel build');
  }
} else {
  console.warn('DATABASE_URL not set — skipping db:migrate at build time');
}

rmSync(outRoot, { recursive: true, force: true });
mkdirSync(funcDir, { recursive: true });
mkdirSync(staticDir, { recursive: true });
writeFileSync(path.join(staticDir, '.gitkeep'), '');

const external = [
  'pg-native',
  'cpu-features',
  'bufferutil',
  'utf-8-validate',
  '@mongodb-js/zstd',
  'node-liblzma',
  'mongodb',
  'kerberos',
  'snappy',
];

const outfile = path.join(funcDir, 'index.cjs');

await esbuild.build({
  entryPoints: [path.join(root, 'scripts/vercel-entry.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'cjs',
  external,
  logLevel: 'info',
  banner: {
    js: '/* Vercel Build Output API bundle — generated by scripts/build-vercel.mjs */',
  },
  footer: {
    js: `
module.exports = globalThis.__okfVercelHandler;
module.exports.config = globalThis.__okfVercelConfig;
`,
  },
});

// CJS bundles cannot use import.meta.url; esbuild lowers it to `import_metaN = {}`.
// just-bash (via @flue/runtime) calls createRequire(import.meta.url) at module init.
const importMetaUrl = 'require("node:url").pathToFileURL(__filename).href';
let bundle = readFileSync(outfile, 'utf8');
const patched = bundle.replace(/import_meta\d+\.url/g, importMetaUrl);
if (patched === bundle) {
  throw new Error('expected import_meta.url placeholders in CJS bundle — esbuild output changed?');
}
writeFileSync(outfile, patched);

const catalogSrc = path.join(root, 'agent-assets');
const catalogDest = path.join(funcDir, 'agent-assets');
cpSync(catalogSrc, catalogDest, { recursive: true });
console.log('Vendored agent-assets into serverless bundle.');

const { size } = statSync(outfile);
if (size < 100_000) {
  throw new Error(`serverless bundle suspiciously small (${size} bytes)`);
}

writeFileSync(
  path.join(funcDir, 'package.json'),
  `${JSON.stringify({ type: 'commonjs' }, null, 2)}\n`,
);

writeFileSync(
  path.join(funcDir, '.vc-config.json'),
  `${JSON.stringify(
    {
      runtime: 'nodejs22.x',
      handler: 'index.cjs',
      launcherType: 'Nodejs',
      maxDuration: 300,
      regions,
    },
    null,
    2,
  )}\n`,
);

writeFileSync(
  path.join(outRoot, 'config.json'),
  `${JSON.stringify(
    {
      version: 3,
      routes: [
        { handle: 'filesystem' },
        { src: '/(.*)', dest: '/index' },
      ],
    },
    null,
    2,
  )}\n`,
);

console.log(
  `Vercel Build Output: .vercel/output/functions/index.func/index.cjs (${(size / 1024 / 1024).toFixed(1)} MB)`,
);
console.log(`Regions: ${regions.join(', ')}`);
console.log(
  'IMPORTANT: Vercel project Root Directory must be "agent-backend" (not the monorepo root).',
);
