/** AUTO-GENERATED by scripts/sync-catalog-agents.mjs — do not edit. */
import { buildCatalogA2aChannel } from '../flue/a2a/create-channel.ts';

export const channel = buildCatalogA2aChannel("kb-qa").channel;
